name: PrivateShopByXAndrei52
main: SaltyPixelDevz\CustomShopUIv2\Shop
version: 4.0.5
api: [3.0.0]
author: SaltyPixelDevz
website: http://saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: "Opens CustomShopUI"
permissions:
  shop.shop:
    default: true
    description: "Allows use of the /shop command"
  shopping:
    description: "Opens §o§cPrivate §bGalaxy shop"
permissions:
  shop.shop:
    default: true
    description: "Allows use of the /shop command"
